Car_Rental_System/Controllers/car_RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Car_Rental_System.Models;

namespace Car_Rental_System.Controllers
{
    public class car_RegistrationController : Controller
    {
        private supercarEntities1 db = new supercarEntities1();

        // GET: car_Registration
        public ActionResult Index()
        {
            return View(db.car_Registration.ToList());
        }

        // GET: car_Registration/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            car_Registration car_Registration = db.car_Registration.Find(id);
            if (car_Registration == null)
            {
                return HttpNotFound();
            }
            return View(car_Registration);
        }

        // GET: car_Registration/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: car_Registration/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,carno,make,model,available")] car_Registration car_Registration)
        {
            var isCarNos = db.car_Registration.FirstOrDefault(e => e.carno == car_Registration.carno);

          if(isCarNos==null)
          {
                if (ModelState.IsValid)
                {
                    db.car_Registration.Add(car_Registration);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

          }
          else
          {
                ViewBag.Message = "Already The Car Number is existed!";
          }

            return View(car_Registration);
        }

        // GET: car_Registration/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            car_Registration car_Registration = db.car_Registration.Find(id);
            if (car_Registration == null)
            {
                return HttpNotFound();
            }
            return View(car_Registration);
        }

        // POST: car_Registration/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,carno,make,model,available")] car_Registration car_Registration)
        {
            if (ModelState.IsValid)
            {
                db.Entry(car_Registration).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(car_Registration);
        }

        // GET: car_Registration/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            car_Registration car_Registration = db.car_Registration.Find(id);
            if (car_Registration == null)
            {
                return HttpNotFound();
            }
            return View(car_Registration);
        }

        // POST: car_Registration/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            car_Registration car_Registration = db.car_Registration.Find(id);
            db.car_Registration.Remove(car_Registration);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Car_Rental_System/Controllers/customersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Car_Rental_System.Models;

namespace Car_Rental_System.Controllers
{
    public class customersController : Controller
    {
        private supercarEntities1 db = new supercarEntities1();

        // GET: customers
        public ActionResult Index()
        {
            return View(db.customers.ToList());
        }

        // GET: customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,custname,address,mobile")] customer customer)
        {
            if (ModelState.IsValid)
            {
                db.customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,custname,address,mobile")] customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            customer customer = db.customers.Find(id);
            db.customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Car_Rental_System/Controllers/returncarController.cs
using Car_Rental_System.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Car_Rental_System.Controllers
{


    public class returncarController : Controller
    {

        supercarEntities1 db = new supercarEntities1();

        // GET: returncar
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Save(returncar recar)
        {
            //if( )
            //{
                db.returncars.Add(recar);

                var car = db.car_Registration.SingleOrDefault(e => e.carno == recar.carno);

                if(car == null)
                {
                    return HttpNotFound("CarNo Not Found");
                }
                car.available = "Yes";
                db.Entry(car).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            //}
            //return View(recar);
        }


        [HttpPost]
        public ActionResult Getid(string carno)
        {

            var carn = (from s in db.rentails
                        where s.carid == carno
                        select new
                        {
                            StartDate = s.sdate,
                            EndDate=s.edate,
                            Custid=s.custid,
                            CarNo=s.carid,
                            Fee=s.fee,
                            ElapsedDays=SqlFunctions.DateDiff("day",s.edate,DateTime.Now)
                        }).ToArray();

            return Json(carn, JsonRequestBehavior.AllowGet);

        }


    }
}

Car_Rental_System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Car Rental System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body style="background-color:burlywood">
    @*<div style="background-image: url('img_girl.jpg');">*@
    <div class="myDiv">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>*@
                    @if (Session["Username"] != null)
                    {
                        if ((bool)Session["isLogin"] == true)
                        {
                            @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Car", "Index", "car_Registration", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Customer", "Index", "customers", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Rent", "Index", "Rent", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("ReturnCar", "Index", "returncar", new { area = "" }, new { @class = "navbar-brand" })
                            <div class="navbar-header" style="float:right !important">
                                @Html.ActionLink("Logout", "Logout", "UserRegistration", new { area = "" }, new { @class = "navbar-brand" })
                            </div>
                        }
                    }

                </div>
                <div class="navbar-header" style="float:right !important">
                    @*@Html.ActionLink("Login", "Login", "UserRegistration", new { area = "" }, new { @class = "navbar-brand" })*@

                </div>
                @*<div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Car", "Index", "car_Registration")</li>
                        <li>@Html.ActionLink("Customer", "Index", "customers")</li>
                        <li>@Html.ActionLink("Rent", "Index", "Rent")</li>
                        <li>@Html.ActionLink("Return Car", "Index", "returncar")</li>
                        <li>@Html.ActionLink("SignUp", "SignUp", "UserRegistration")</li>
                    </ul>
                </div>*@
            </div>
        </div>
    </div>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Madhan Pantrangam</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>